In [31]:
import pandas as pd
import numpy as np

In [196]:
# importing excel

file_path = 'C:/Users/jongm/Downloads/transcribed_Checklist_17-N-0145.xlsx';

df = pd.read_excel(file_path, sheet_name='Sheet1'); #header=None
#print (df)
range?
df.head(100)

#df?

#pd.read_excel(file_path, sheet_name=0, header=0, names=None, index_col=None, parse_cols=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skip_footer=0, skipfooter=0, convert_float=True, mangle_dupe_cols=True, **kwds);

,Subject ID,Timepoints,CBC/diff/plts
0,P001,Screening,"low WMC; low RBC, low platelets"
1,P001,Screening,NaN
2,P001,Baseline,NaN
3,P002,Screening,low platelet count (140)
4,P002,Baseline,Subject withdrawn prior to completion
5,P003,Screening,NaN
6,P003,Baseline,elevated RDW (15.2 norm 14.4 and low MCHC 32.
7,P003,Week 0,NaN
8,P003,Week 3,NaN
9,P003,Week 6,NaN
10,P003,Week 12,NaN
11,P003,Week 18,NaN
12,P003,Week 24,low HGB (10.9) on AE log and CTDB AE log
13,P004,Screening,low HGB (10.6); low HTC (33.2); low MCV (65.2)...
14,P004,Screening,elevated RBC (5.41); low MCV (66.5); low MHC (...
15,P004,Baseline,"Elevated RDW (18.2), low HGB (10.6), low HCT (..."
16,P004,Week 0,low HGB 9.7 low HCT 30.2; low MCV 66.5; low M...
17,P004,Week 3,low HGB 10.1 Grade 2; low HCT 31.6; low MCV ...
18,P004,Week 6,low HGB 10.5 Grade 2 low HCT 33.6; low MCV 69...
19,P004,Week 12,low HGB 9.9 Grade 2 on AE log and in CTDB AE l...
20,P004,Week 18,low MCV 68.9; low MCH 22.3; elevated RDW 19.3;...
21,P004,Week 24,low HGB 9.7 grade 2 on AE log and in CTDB AE l...
22,P005,Screening,elevated neutrophils (68.2); low monocytes (5....
23,P005,Baseline,neutrophil absolute (5.79)
24,P005,Week 0,elevated immature granulocytes (0.05 norm 0.0-...
25,P005,Week 3,low HGB on AE log and in CTDB AE log; (13.5 n...
26,P005,Week 6,low HGB 13.4(13.5 norm 13.7-17.5 on AE log an...
27,P005,"Week 12 (May 24, 2019) visit via phone. No la...",NaN
28,P006,Screening,elevated MCV (99.4); elevated MCH (33.2); elev...
29,P006,Baseline,elevated MCV (100); elevated MCH (33.6); eleva...
...,...,...,...
70,P003,Baseline,NaN
71,P003,Week 0,NaN
72,P003,Week 3,NaN
73,P003,Week 6,NaN
74,P003,Week 12,NaN
75,P003,Week 18,NaN
76,P003,Week 24,NaN
77,P004,Screening,NaN
78,P004,Screening,NaN
79,P004,Baseline,NaN
80,P004,Week 0,NaN
81,P004,Week 3,NaN
82,P004,Week 6,NaN
83,P004,Week 12,NaN
84,P004,Week 18,NaN
85,P004,Week 24,NaN
86,P005,Screening,NaN
87,P005,Baseline,NaN
88,P005,Week 18,NaN
89,P005,Week 21,NaN
90,P005,Week 24,NaN
91,P005,"Week 12 (May 24, 2019) visit via phone. No la...",NaN
92,P006,Screening,NaN
93,P006,Baseline,NaN
94,P006,Week 2,NaN
95,Subject ID,Timepoints,D-Dimer
96,P001,Screening,NaN
97,P001,Screening,elevated
98,P001,Baseline,NaN
99,P002,Screening,NaN

In [187]:
from collections import Counter
c = Counter([0,1,3,3,3,0])
print(c)
print(c[3])

temp_A = 0

temp_A = 3 if temp_A == 0 else 2

print("\ntemp_A:", temp_A, "\n")

x = 2
y = 4

parity = "even" if x % 2 is 0 else "odd"

print(parity)

print(x is 2)

print("\nAND \n", x is 2 and y)
print(x == 3 and y == 4)
print("\nOR \n", x is 2 or y)
print(x or y)
print(x == 3 or y == 4)

print("\nlambda usage\n", (lambda x: x if x+1 is not 0 else 0)(12))
print((lambda x: x+1)(10))
print(x)

Counter({3: 3, 0: 2, 1: 1})
3

temp_A: 3

even
True

AND
 4
False

OR
 True
2
True

lambda usage
 12
11
2